In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(dataset)

       Province   Age        Wage Life Insured
0        Banten  24.0   5000000.0          Yes
1   DKI Jakarta   NaN   3400000.0           No
2    Jawa Barat  60.0   7350000.0           No
3        Banten  34.0   3500000.0           No
4    Jawa Barat  58.0         NaN          Yes
5   DKI Jakarta   NaN   8000000.0           No
6        Banten  21.0   5500000.0           No
7        Banten  44.0  10000000.0          Yes
8    Jawa Barat  40.0   9000000.0          Yes
9   DKI Jakarta  51.0  10500000.0          Yes
10       Banten  32.0         NaN           No
11       Banten  30.0   6400000.0           No
12   Jawa Barat  30.0         NaN           No
13  DKI Jakarta  19.0   2200000.0          Yes
14  DKI Jakarta  25.0   4500000.0          Yes


In [4]:
print(x)

[['Banten' 24.0 5000000.0]
 ['DKI Jakarta' nan 3400000.0]
 ['Jawa Barat' 60.0 7350000.0]
 ['Banten' 34.0 3500000.0]
 ['Jawa Barat' 58.0 nan]
 ['DKI Jakarta' nan 8000000.0]
 ['Banten' 21.0 5500000.0]
 ['Banten' 44.0 10000000.0]
 ['Jawa Barat' 40.0 9000000.0]
 ['DKI Jakarta' 51.0 10500000.0]
 ['Banten' 32.0 nan]
 ['Banten' 30.0 6400000.0]
 ['Jawa Barat' 30.0 nan]
 ['DKI Jakarta' 19.0 2200000.0]
 ['DKI Jakarta' 25.0 4500000.0]]


In [5]:
print(y)

['Yes' 'No' 'No' 'No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No'
 'Yes' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(
        missing_values=np.nan, 
        strategy='mean'
        )
imputer = imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['Banten' 24.0 5000000.0]
 ['DKI Jakarta' 36.0 3400000.0]
 ['Jawa Barat' 60.0 7350000.0]
 ['Banten' 34.0 3500000.0]
 ['Jawa Barat' 58.0 6279166.666666667]
 ['DKI Jakarta' 36.0 8000000.0]
 ['Banten' 21.0 5500000.0]
 ['Banten' 44.0 10000000.0]
 ['Jawa Barat' 40.0 9000000.0]
 ['DKI Jakarta' 51.0 10500000.0]
 ['Banten' 32.0 6279166.666666667]
 ['Banten' 30.0 6400000.0]
 ['Jawa Barat' 30.0 6279166.666666667]
 ['DKI Jakarta' 19.0 2200000.0]
 ['DKI Jakarta' 25.0 4500000.0]]


In [8]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct= ColumnTransformer(transformers=[('province_encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 24.0 5000000.0]
 [0.0 1.0 0.0 36.0 3400000.0]
 [0.0 0.0 1.0 60.0 7350000.0]
 [1.0 0.0 0.0 34.0 3500000.0]
 [0.0 0.0 1.0 58.0 6279166.666666667]
 [0.0 1.0 0.0 36.0 8000000.0]
 [1.0 0.0 0.0 21.0 5500000.0]
 [1.0 0.0 0.0 44.0 10000000.0]
 [0.0 0.0 1.0 40.0 9000000.0]
 [0.0 1.0 0.0 51.0 10500000.0]
 [1.0 0.0 0.0 32.0 6279166.666666667]
 [1.0 0.0 0.0 30.0 6400000.0]
 [0.0 0.0 1.0 30.0 6279166.666666667]
 [0.0 1.0 0.0 19.0 2200000.0]
 [0.0 1.0 0.0 25.0 4500000.0]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[1 0 0 0 1 0 0 1 1 1 0 0 0 1 1]


In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [13]:
print(x_train)

[[0.0 1.0 0.0 51.0 10500000.0]
 [0.0 1.0 0.0 25.0 4500000.0]
 [0.0 0.0 1.0 58.0 6279166.666666667]
 [0.0 0.0 1.0 60.0 7350000.0]
 [0.0 1.0 0.0 19.0 2200000.0]
 [1.0 0.0 0.0 32.0 6279166.666666667]
 [1.0 0.0 0.0 44.0 10000000.0]
 [1.0 0.0 0.0 30.0 6400000.0]
 [1.0 0.0 0.0 34.0 3500000.0]
 [1.0 0.0 0.0 24.0 5000000.0]
 [0.0 1.0 0.0 36.0 8000000.0]
 [0.0 0.0 1.0 30.0 6279166.666666667]]


In [14]:
print(x_test)

[[0.0 1.0 0.0 36.0 3400000.0]
 [1.0 0.0 0.0 21.0 5500000.0]
 [0.0 0.0 1.0 40.0 9000000.0]]


In [15]:
print(y_train)

[1 1 1 0 1 0 1 0 0 1 0 0]


In [16]:
print(y_test)

[0 0 1]


In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [18]:
print(x_train)

[[0.0 1.0 0.0 1.0950272892781363 1.7817150841237404]
 [0.0 1.0 0.0 -0.9265615524661149 -0.7987925559448409]
 [0.0 0.0 1.0 1.6393012082092808 -0.03360035989672672]
 [0.0 0.0 1.0 1.7948080421896078 0.4269485730877352]
 [0.0 1.0 0.0 -1.393082054407096 -1.7879871513044636]
 [1.0 0.0 0.0 -0.3822876335349704 -0.03360035989672672]
 [1.0 0.0 0.0 0.5507533703469917 1.5666727807846919]
 [1.0 0.0 0.0 -0.5377944675152975 0.018368196743543185]
 [1.0 0.0 0.0 -0.2267807995546434 -1.2288771626229378]
 [1.0 0.0 0.0 -1.0043149694562785 -0.5837502526057924]
 [0.0 1.0 0.0 -0.07127396557431637 0.7065035674284982]
 [0.0 0.0 1.0 -0.5377944675152975 -0.03360035989672672]]
